[theme]
base = "light"
primaryColor = "#201d1d"
backgroundColor = "#fdfcfc"
secondaryBackgroundColor = "#f1eeee"
textColor = "#201d1d"
linkColor = "#201d1d"
font = "monospace"
headingFont = "monospace"
codeFont = "monospace"
baseRadius = "none"
buttonRadius = "small"
borderColor = "#d8d5d5"
showWidgetBorder = true
showSidebarBorder = false
